apiVersion: argoproj.io/v1alpha1 # Changed from apps/v1
kind: Rollout
metadata:
  name: rolloutapp
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: rolloutapp
  template:
    metadata:
      labels:
        app: rolloutapp
    spec:
      containers:
        - image: gcr.io/demochat101/express-microservice:d7d68eb
          name: rolloutapp
          ports:
            - containerPort: 3000
  minReadySeconds: 30
  strategy:
  # ----- Everything above this comment are the same as a deployment -----
    canary: # A new field that used to provide configurable options for a Canary strategy
      steps:
      - setWeight: 50
      - pause: {}
